In [ ]:
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt

sys.path.append(os.path.abspath(".."))
from src.utils.preprocess import load_raw_data

pd.set_option('display.max_columns', None)

In [52]:
test_df = pd.read_csv(os.path.join("..", "data", "test.csv"))
train_df = pd.read_csv(os.path.join("..", "data", "train.csv"))

In [53]:
test_df.head()

,Unnamed: 0,Age,Match Played,Match Started,Minutes Played,Minutes Played / 90,Goals,Assists,Goals + Assists,Non-Penality Goals,Penalty Kick Goals,Penalty Kick Attempted,Yellow Cards,Red Cards,Goals Per 90 Minutes,Assists Per 90 Minutes,G+A Per 90 Minutes,Non-Penality Goals Per 90 Minutes,Non-Penalty Goals + Assists/90,Value,DF,FW,GK,MF,Squad_Rank
0,2,25,28,21,1965,21.8,0,3,3,0,0,0,7,0,0.00,0.14,0.14,0.00,0.14,25000000.0,0,0,0,1,10.0
1,3,26,22,15,1409,15.7,1,1,2,1,0,0,4,0,0.06,0.06,0.13,0.06,0.13,20000000.0,1,0,0,0,17.0
2,4,22,29,12,1097,12.2,2,2,4,2,0,0,0,0,0.16,0.16,0.33,0.16,0.33,22000000.0,0,0,0,1,11.0
3,7,27,35,35,2995,33.3,2,1,3,2,0,0,5,0,0.06,0.03,0.09,0.06,0.09,20000000.0,1,0,0,0,7.0
4,8,23,37,37,3109,34.5,4,7,11,4,0,0,7,1,0.12,0.20,0.32,0.12,0.32,40000000.0,1,0,0,1,6.0

In [ ]:
def feature_engineering(input_df):
    # Filter only FW & MF
    df = input_df[(input_df["FW"] == 1) | (input_df["MF"] == 1)]
    df = df.drop(columns=["DF", "GK"])

    # Drop columns
    df = df.drop(columns=["Goals + Assists", "Penalty Kick Attempted", "Yellow Cards", "Red Cards", "G+A Per 90 Minutes", "Minutes Played / 90"])

    # Bin "Match Played"
    df["Experience_Level"] = pd.cut(
        df["Match Played"], 
        bins=[0, 10, 20, 30, 100], 
        labels=["Level 1", "Level 2", "Level 3", "Level 4"]
    )
    df = df.drop(columns=["Match Played"])

    # Binarize "Penalty Kick Goals"


    # Min-Max Scale "Match Started", "Minutes Played"


    # Log Transform "Goals", "Assists", "Non-Penalty Goals"


    # Log Transform (f(x) = ln(x + 1)) "Goals Per 90 Minutes", "Assists Per 90 Minutes", "Non-Penalty Goals Per 90 Minutes", "Non-Penalty Goals + Assists/90"


    return df

In [55]:
temp_df = feature_engineering(train_df)

In [56]:
# temp_df.head()
temp_df.info()

<class 'pandas.DataFrame'>
Index: 3760 entries, 1 to 5612
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         3760 non-null   int64
 1   Age                                3760 non-null   int64
 2   Match Started                      3760 non-null   int64
 3   Minutes Played                     3760 non-null   int64
 4   Minutes Played / 90                3760 non-null   float64
 5   Goals                              3760 non-null   int64
 6   Assists                            3760 non-null   int64
 7   Non-Penality Goals                 3760 non-null   int64
 8   Penalty Kick Goals                 3760 non-null   int64
 9   Goals Per 90 Minutes               3760 non-null   float64
 10  Assists Per 90 Minutes             3760 non-null   float64
 11  Non-Penality Goals Per 90 Minutes  3760 non-null   float64
 12  Non-Penalty Goals + Assists/90     3760 non-null   float64
 13  Value                              3760 non-null   float64
 14  FW                                 3760 non-null   int64
 15  MF                                 3760 non-null   int64
 16  Squad_Rank                         3760 non-null   int64
 17  Match_Played_Range                 3760 non-null   category
dtypes: category(1), float64(6), int64(11)
memory usage: 532.5 KB

In [58]:
temp_df.head()

,Unnamed: 0,Age,Match Started,Minutes Played,Minutes Played / 90,Goals,Assists,Non-Penality Goals,Penalty Kick Goals,Goals Per 90 Minutes,Assists Per 90 Minutes,Non-Penality Goals Per 90 Minutes,Non-Penalty Goals + Assists/90,Value,FW,MF,Squad_Rank,Match_Played_Range
1,2,24,1,121,1.3,0,0,0,0,0.00,0.00,0.00,0.00,18000000.0,0,1,9,0
3,5,21,25,2222,24.7,6,1,6,0,0.24,0.04,0.24,0.28,28000000.0,0,1,10,3
5,8,21,0,349,3.9,0,0,0,0,0.00,0.00,0.00,0.00,3500000.0,0,1,11,1
6,10,26,20,1692,18.8,1,1,1,0,0.05,0.05,0.05,0.11,22000000.0,0,1,4,2
7,11,22,29,2329,25.9,2,1,2,0,0.08,0.04,0.08,0.12,35000000.0,0,1,7,3